# Generated by Django 5.1.2 on 2024-11-10 02:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comidas", "0002_alter_post_data_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-data"]},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-data"]},
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("descricao", models.CharField(max_length=1000)),
                ("post", models.ManyToManyField(to="comidas.post")),
            ],
        ),
    ]
